workflows:
  android-workflow:
    name: Weather App Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
        JAVA_HOME: /Applications/Android Studio.app/Contents/jre/Contents/Home
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure gradlew is executable
        script: chmod +x ./gradlew
      - name: Fix Room schema location
        script: |
          echo "android.enableSeparateAnnotationProcessing=true" >> gradle.properties
          echo "android {
                  defaultConfig {
                      javaCompileOptions {
                          annotationProcessorOptions {
                              arguments += ['room.schemaLocation': projectDir.path + '/schemas']
                          }
                      }
                  }
                }" >> app/build.gradle
      - name: Remove debug-db dependency
        script: sed -i.bak '/com.amitshekhar.android:debug-db/d' app/build.gradle
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk


















