workflows:
  android-workflow:
    name: Build Android Project
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk  # 替换为 Codemagic 提供的路径
    scripts:
      - name: Verify Java version
        script: java -version
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk




















