workflows:
  native-android:
    name: Native Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
        JAVA_HOME: /Applications/Android Studio.app/Contents/jre/Contents/Home
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure gradlew is executable
        script: chmod +x ./gradlew
      - name: Remove problematic debug-db dependency
        script: sed -i '' '/com.amitshekhar.android:debug-db/d' app/build.gradle
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk














