workflows:
  android-workflow:
    name: Build with Latest Gradle
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64  # 使用 Java 11
    scripts:
      - name: Update Gradle Wrapper to Latest
        script: ./gradlew wrapper --gradle-version 7.4.2 --distribution-type all
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk



















