workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "io.codemagic.sample.androidnative"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure gradlew is executable
        script: chmod +x ./gradlew
      - name: Build Android release
        script: ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.aab


