workflows:
  native-android:
    name: Native Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure gradlew is executable
        script: chmod +x ./gradlew
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Build Android release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk




