workflows:
  android-workflow:
    name: Android Build with Fixes
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
        JAVA_HOME: /Applications/Android Studio.app/Contents/jre/Contents/Home
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Ensure gradlew is executable
        script: chmod +x ./gradlew
      - name: Fix WeatherRecyclerAdapter constructor
        script: |
          sed -i.bak "s/new WeatherRecyclerAdapter(this)/new WeatherRecyclerAdapter(this, new ArrayList<>(), null, new ArrayList<>())/" app/src/main/java/com/seancoyle/weatherapp/WeatherForecastListActivity.java
      - name: Fix Room Database warnings
        script: |
          echo "android.enableSeparateAnnotationProcessing=true" >> gradle.properties
          echo "room.schemaLocation=\$projectDir/schemas" >> app/build.gradle
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
















